version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - './src:/application'
            - './dbdata:/var/lib/mysql'
            - './scripts/init.sql:/docker-entrypoint-initdb.d/1.sql'
            - './scripts/classicmodels.sql:/docker-entrypoint-initdb.d/2.sql'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - '3002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './src:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '3000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        environment:
            - PHP_FPM_CLEAR_ENV=no
        env_file:
            - .env
        volumes:
            - './src:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        restart: always
        depends_on:
            - mysql
        ports:
            - '8080:80'